start:	
	gcc -Wall -g -c board.c -o obj/Debug/board.o
	gcc -Wall -g -c db.c -o obj/Debug/db.o
	gcc -Wall -g -c list.c -o obj/Debug/list.o
	gcc -Wall -g -c main.c -o obj/Debug/main.o
	gcc -Wall -g -c task.c -o obj/Debug/task.o
	g++  -o bin/Debug/ToDoList obj/Debug/board.o obj/Debug/db.o obj/Debug/list.o obj/Debug/main.o obj/Debug/task.o